spring:
  application:
    name: 'Backend'
  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
    username: user
    password: password
    platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
server:
  port: 8080
  error:
    include-stacktrace: never
    include-exception: false
    include-binding-errors: never
logging:
  pattern:
    dateformat: hh:mm:ss